// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddUser(ctx context.Context, arg AddUserParams) (User, error)
	CreateOrderItems(ctx context.Context, arg CreateOrderItemsParams) ([]OrderItem, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	DeleteProduct(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error)
	DeleteUser(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error)
	FindProductsByID(ctx context.Context, id pgtype.UUID) (Product, error)
	ListProducts(ctx context.Context) ([]Product, error)
	PlaceOrder(ctx context.Context, userID pgtype.UUID) (Order, error)
}

var _ Querier = (*Queries)(nil)
