// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addUser = `-- name: AddUser :one
INSERT INTO users (
    first_name,
    last_name,
    email,
    password
) VALUES (
    $1,
    $2,
    $3,
    $4
) RETURNING id, first_name, last_name, created_at, password, email
`

type AddUserParams struct {
	FirstName string `json:"first_name"`
	LastName  string `json:"last_name"`
	Email     string `json:"email"`
	Password  string `json:"password"`
}

func (q *Queries) AddUser(ctx context.Context, arg AddUserParams) (User, error) {
	row := q.db.QueryRow(ctx, addUser,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.Password,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.CreatedAt,
		&i.Password,
		&i.Email,
	)
	return i, err
}

const createOrderItems = `-- name: CreateOrderItems :many
INSERT INTO order_items (order_id, product_id, quantity, price_per_product_in_cents)
SELECT
  $1::uuid,
  (x->>'product_id')::uuid,
  (x->>'quantity')::int,
  (x->>'price_per_product_in_cents')::int
FROM jsonb_array_elements($2::jsonb) AS x
RETURNING id, order_id, product_id, quantity, price_per_product_in_cents
`

type CreateOrderItemsParams struct {
	Column1 pgtype.UUID `json:"column_1"`
	Column2 []byte      `json:"column_2"`
}

func (q *Queries) CreateOrderItems(ctx context.Context, arg CreateOrderItemsParams) ([]OrderItem, error) {
	rows, err := q.db.Query(ctx, createOrderItems, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrderItem
	for rows.Next() {
		var i OrderItem
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.ProductID,
			&i.Quantity,
			&i.PricePerProductInCents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (
    name,
    price_in_cents,
    quantity
) VALUES (
    $1,
    $2,
    $3
) RETURNING id, name, price_in_cents, quantity, created_at
`

type CreateProductParams struct {
	Name         string `json:"name"`
	PriceInCents int32  `json:"price_in_cents"`
	Quantity     int32  `json:"quantity"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct, arg.Name, arg.PriceInCents, arg.Quantity)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PriceInCents,
		&i.Quantity,
		&i.CreatedAt,
	)
	return i, err
}

const deleteProduct = `-- name: DeleteProduct :one
DELETE FROM products WHERE id=$1 RETURNING id
`

func (q *Queries) DeleteProduct(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, deleteProduct, id)
	err := row.Scan(&id)
	return id, err
}

const deleteUser = `-- name: DeleteUser :one
DELETE FROM users WHERE id = $1 RETURNING id
`

func (q *Queries) DeleteUser(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, deleteUser, id)
	err := row.Scan(&id)
	return id, err
}

const findProductsByID = `-- name: FindProductsByID :one
SELECT
    id, name, price_in_cents, quantity, created_at
FROM
    products
WHERE
    id = $1
`

func (q *Queries) FindProductsByID(ctx context.Context, id pgtype.UUID) (Product, error) {
	row := q.db.QueryRow(ctx, findProductsByID, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PriceInCents,
		&i.Quantity,
		&i.CreatedAt,
	)
	return i, err
}

const getOrderById = `-- name: GetOrderById :one
SELECT
    o.id, o.user_id, o.status, o.created_at,
    COALESCE(
      jsonb_agg(
        jsonb_build_object(
          'product_id', oi.product_id,
          'quantity', oi.quantity,
          'product', p.name,
          'original_price', p.price_in_cents
        )
      ) FILTER (WHERE oi.id IS NOT NULL),
      '[]'::jsonb
    ) AS order_items,
    COALESCE(
        SUM(oi.quantity * oi.price_per_product_in_cents),
        0
    )::int AS total_price_in_cents
FROM
    orders o
LEFT JOIN
    order_items oi ON oi.order_id = o.id
LEFT JOIN
    products p ON oi.product_id = p.id
WHERE
    o.id=$1
GROUP BY
    o.id
`

type GetOrderByIdRow struct {
	ID                pgtype.UUID        `json:"id"`
	UserID            pgtype.UUID        `json:"user_id"`
	Status            int16              `json:"status"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	OrderItems        interface{}        `json:"order_items"`
	TotalPriceInCents int32              `json:"total_price_in_cents"`
}

func (q *Queries) GetOrderById(ctx context.Context, id pgtype.UUID) (GetOrderByIdRow, error) {
	row := q.db.QueryRow(ctx, getOrderById, id)
	var i GetOrderByIdRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.CreatedAt,
		&i.OrderItems,
		&i.TotalPriceInCents,
	)
	return i, err
}

const getProductsByIds = `-- name: GetProductsByIds :many
SELECT id, name, price_in_cents, quantity, created_at FROM products WHERE id = ANY($1::uuid[])
`

func (q *Queries) GetProductsByIds(ctx context.Context, dollar_1 []pgtype.UUID) ([]Product, error) {
	rows, err := q.db.Query(ctx, getProductsByIds, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PriceInCents,
			&i.Quantity,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProducts = `-- name: ListProducts :many
SELECT
    id, name, price_in_cents, quantity, created_at
FROM
    products
`

func (q *Queries) ListProducts(ctx context.Context) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PriceInCents,
			&i.Quantity,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const placeOrder = `-- name: PlaceOrder :one
INSERT INTO orders (user_id) VALUES ($1) RETURNING id, user_id, status, created_at
`

func (q *Queries) PlaceOrder(ctx context.Context, userID pgtype.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, placeOrder, userID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
